# Generated by Django 3.2.2 on 2021-05-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_usn', models.CharField(max_length=11)),
                ('student_mobile', models.CharField(max_length=12)),
                ('student_email', models.EmailField(default='', max_length=100)),
                ('student_dept', models.CharField(max_length=5)),
                ('student_sem', models.CharField(max_length=200)),
                ('student_exam_type', models.CharField(max_length=200)),
                ('student_subject', models.CharField(max_length=200)),
                ('student_subject_code', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'final',
            },
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=111)),
                ('phone', models.CharField(default='', max_length=12)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.semesters')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('backlog', 'Backlog Exam'), ('improvement', 'Improvement Exam'), ('year_back', 'Year back Exam')], max_length=100)),
                ('subject_code', models.CharField(choices=[('16CS302', '16CS302'), ('16CS303', '16CS303')], max_length=100)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.departments')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.semesters')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.subjects')),
            ],
        ),
    ]
