# Generated by Django 3.2.6 on 2021-11-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210825_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject_code',
            field=models.CharField(choices=[('16CS302', '16CS302'), ('16CS303', '16CS303'), ('16CS204', '16CS204'), ('17CS300', '17CS300')], max_length=100),
        ),
    ]
