# Generated by Django 3.2.6 on 2021-11-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_student_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_code_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('sub_code', models.CharField(max_length=10)),
            ],
        ),
    ]
